### ISSUE TITLE
rust-lld: error: no memory region specified for section '.ARM.exidx'

### ISSUE THREAD

**Issue by danksz** [astraw/nucleo-h743zi#1]
The build is failing with:
```
...
= note: rust-lld: error: no memory region specified for section '.ARM.exidx'          

error: linking with `rust-lld` failed: exit code: 1
...
```
It seems that this [PR](https://github.com/rust-embedded/cortex-m-rt/pull/170) in `cortex-m-rt` fix the issue. So, the crate `cortex-m-rt` shall be updated to >= 0.6.8 version.

The following update `cortex-m-rt` crate to the up-to-date release.
```
$ cargo update -p cortex-m-rt
```

**Comment by astraw** [comment]
This has been fixed for some time, at least since a7d363283422b1f516d51e8d4729a8b28f3b17bf. Apologies for the delay in responding to your issue.
