### ISSUE TITLE
Integrate examples with HAL crate?

### ISSUE THREAD

**Issue by robamu** [astraw/nucleo-h743zi#7]
As requested in #5 and #4 , it might be worth a thought to move the examples into the HAL crate. I think there are some trade-offs to consider:

- Having a board specific example makes it really easy to get started with a new board because the examples work out of the box. Some of the examples in the HAL crate are board specific, others look more generic. It might become necessary to make adaption on it. I'm relatively new to embedded HAL and I was glad that this repository existed and worked right out of the box.
- The supplementary files in `.vscode` and the `openocd` files make it really easy to get started with IDEs / graphical debugging support right away and have a good base line to develop more complex applications, The HAL crate does not offer that (and it would not be the right place for it in my opinion), so this is a big advantage of a dedicated example repository as well 
- It's easier to provide a tailored `memory.x` file for each board. I don't know the other boards well enough, so I am not 100 % sure that the memory.x file provided in https://github.com/astraw/stm32h7xx-hal/blob/master/memory.x works  for the board. I might compare it to the linker script I used for C++ applications for that board. UPDATE: The file actually works, see https://github.com/astraw/nucleo-h743zi/pull/8 
- Maintenance effort is a big drawback of course.

**Comment by astraw** [comment]
These are very good points. For example, I am interested in your .vscode and openocd files which I know from experience can be tricky to setup. So, it is nice to have that working out of the box.

This convinces me that we should keep this repo as a board-specific "first step". Perhaps the ideal solution is to update the README to describe this goal clearly and then direct them to https://github.com/stm32-rs/stm32h7xx-hal as they get more advanced. What do you think about that?

**Comment by robamu** [comment]
I like the approach. I'll try copying some of the examples into this repo soon to check how well it works. I might still introduce some more board specific examples (e.g. I2C, serial logger) which can be tricky to setup with the generic example code because this board is our go-to dev board for testing out new concepts (and for me to learn all aspects of embedded rust) and possibly for education soon as well.

**Comment by astraw** [comment]
I updated the README (a89b5e6ec6f6075949bfc3f91a5e653bc6a0488a) and fixed the blinky example (29e66f53bf05911ba434ad45d70b15d79d1d816a) to reflect these better defined goals, and I am closing the issue. Thanks for helping clarify all this.

Please reopen this issue or a start a new one if something comes up and update the README if you find any further differences between the boards.

I think the Nucleo boards are great for education. For starting out, you can compile code using the Mbed Online Compiler, and download the resulting binary, and then copy this onto the target Nucleo board. All without installing a single piece of software on the students computer. This is really amazing. Students with no experience whatsoever can go from zero to blinky in a couple minutes.
